#!/bin/bash

alias ca='vi ~/.bash/aliases'
alias src='source ~/.bashrc'

alias l="ls -BF --ignore='*.pyc'"
alias ll='ls -l -BF'
alias la='ls -AF'

# .. goes up a directory
alias ..='cd ..'
# - goes back a directory
alias -- -='cd -'

alias rm='rm -i'

alias v="vim"
alias vi="vim"
# testing!!!
alias vim='nvim'

# use hub (see ~/src/hub)
alias git=hub

alias iv='viewnior'
alias view='viewnior'

alias u="amixer set Master 5%+ | grep -o '\[.*%\]'"
alias d="amixer set Master 5%- | grep -o '\[.*%\]'"

alias armory="python /usr/share/armory/ArmoryQt.py --offline"

alias radio3="mplayer -playlist http://www.bbc.co.uk/radio/listen/live/r3_aaclca.pls"

function make_ssh_tunnel {
    # make a tunnel for rdesktop to go through
    # run it in the background and return the socket file
    # https://stackoverflow.com/questions/2241063/bash-script-to-setup-a-temporary-ssh-tunnel
    socket_file='/tmp/rdesktop_ssh_socket'
    ssh -C -L 3388:see4-82:3389 eeaol@gw -Nfo ExitOnForwardFailure=yes -M -S $socket_file
    }

function exit_ssh_tunnel {
    # exit the ssh tunnel created with make_ssh_tunnel
    ssh -S $socket_file -O exit eeaol@gw
    }

function rdesktop_command {
    make_ssh_tunnel
    nohup rdesktop localhost:3388 -d DS -u eeaol -a 16 -f -P -x broadband -z > /dev/null &
    # exit_ssh_tunnel
    }

alias piv='rdesktop_command'
alias dad='ssh -tX doug-and-duck "cd $PWD; bash -l"'

function start_ipython_tunnel {
    # make a tunnel from this machine to doug-and-duck
    # so that we can run an ipython notebook on doug-and-duck
    # and interact with it on this machine (localhost)

    # create the tunnel in the background
    ssh -X -N -f -L localhost:8898:localhost:8898 doug-and-duck

    # start the notebook on doug-and-duck
    ## command to setup canopy
    canopy_up='source $HOME/src/canopy/User/bin/activate'
    notebook_up='PYTHONPATH=$HOME/code/ ipython notebook --no-browser --port=8898 --notebook-dir=$HOME/code/notebooks &'
    ssh -f doug-and-duck "${canopy_up}; ${notebook_up}"

    # wait for notebook to get started
    echo "spinning up notebook on doug-and-duck..."
    sleep 2

    # connect to the notebook on this machine
    firefox -no-remote -P ipython & disown
    # I created a firefox profile called 'ipython' that has its
    # homepage set to '127.0.0.1:8898'. This command starts a new
    # instance of firefox, i.e. independent of any current firefox
    # process, with this ipython profile. What should happen is a
    # new firefox window opens with the notebook server open.
    }

# https://gist.github.com/evansd/1639992
function substitute {
    if [ -z "$1" -o -z "$2" ]; then
        echo "Usage: substitue FROM_STRING TO_STRING [OPTION]..."
        echo
        echo "Replace all occurances of FROM_STRING (a sed-compatible regular"
        echo "expression) with TO_STRING in all files for which ack-grep matches"
        echo "FROM_STRING."
        echo
        echo "Any additional options are passed directly to ack-grep (e.g.,"
        echo " --type=html would only run the substitution on html files)."
        return 1
    fi
    # Escape forward slashes for sed
    FROM_STRING=${1/\//\\/}
    TO_STRING=${2/\//\\/}
    shift 2
    ack -l --print0 "$@" "$FROM_STRING" | xargs -0 -n 1 sed -i -e "s/$FROM_STRING/$TO_STRING/g"
}
